### PR TITLE
Support for LTS 3 using GHC 7.10.2

### PR DESCRIPTION
**Pull request by fatlazycat**

### CODE REVIEW

**Comment by snoyberg** [comment]
Thanks. Pinging @DanBurton. I don't actually have Hackage maintainer access for this package.

**Comment by DanBurton** [comment]
I've added @snoyberg, @chrisdone, and @borsboom as hackage maintainers.

**Comment by DanBurton** [comment]
I made one small tweak (5c4fa0f) and uploaded 0.1.6.

**Comment by fatlazycat** [comment]
Thanks

**Pull request merged**
